#!/usr/bin/env python3
"""
exact_k2.py -- Exact value of A^P_nd(n,d,2) by exhaustive enumeration.

For k=2 the complete enumeration is feasible even when U_n is large: every
subgroup of order 4 is either Z_4 (cyclic, generated by one element of order
4) or Z_2 x Z_2 (generated by two commuting involutions). It is therefore
enough to run over the elements of order 4 and over the pairs of commuting
involutions; no lattice walk is needed.

The result is the exact value only when CBC proves optimality, that is, when
it finishes before the time limit. PuLP reports the status "Optimal" also when
CBC stops on the time limit holding a feasible solution, so the script checks
the solution status as well and reports the value as exact only in the first
case; otherwise it is a lower bound.

    python exact_k2.py --n 5 --d 4 --aq 9
    python exact_k2.py --n 6 --d 4 --aq 21

Writes results_<ndk>_exact.json and clique_<ndk>_exact.{pkl,json}.
"""
import argparse, re, json, pickle, time
from itertools import permutations, product
from collections import defaultdict
import psc_gen

ap = argparse.ArgumentParser()
ap.add_argument("--n", type=int, required=True)
ap.add_argument("--d", type=int, required=True)
ap.add_argument("--aq", type=int, required=True)
ap.add_argument("--reference", type=int, default=None,
                help="a reference value to print alongside the result (optional)")
ap.add_argument("--time-limit", type=int, default=3600)
ap.add_argument("--verbose", action="store_true",
                help="show the CBC log on screen while it runs")
a = ap.parse_args()

n, d, k = a.n, a.d, 2
G = psc_gen.make(n)
prod, e, idp = G['prod'], G['e'], G['idp']
max_shared = 2**((2*k - d)//2) - 1

bad = G['check_assoc']()
assert bad == 0, f"ABORTED: the group operation is not associative ({bad}/5000)"
print("[check] operation verified associative (0/5000)")
print(f"Case ({n},{d},2): order 4, threshold |core cap core| <= {max_shared}\n")

allU = [(v, p) for v in product((0, 1), repeat=n) for p in permutations(range(n))]
print(f"|U_{n}| = {len(allU)}")

def closure(gens):
    S = {e}; fr = list(gens)
    while fr:
        x = fr.pop()
        if x in S: continue
        S.add(x)
        if len(S) > 4: return None
        for y in list(S):
            for pr in (prod(x, y), prod(y, x)):
                if pr not in S: fr.append(pr)
    return frozenset(S)

t0 = time.time()
involutions = [g for g in allU if g != e and prod(g, g) == e]
order4 = [g for g in allU if prod(g, g) != e and prod(prod(g, g), prod(g, g)) == e]
print(f"  involutions: {len(involutions)} | elements of order 4: {len(order4)}  ({time.time()-t0:.0f}s)")

t0 = time.time(); subgroups = set()
for g in order4:                                        # Z_4
    H = closure([g])
    if H and len(H) == 4: subgroups.add(H)
print(f"  cyclic Z_4: {len(subgroups)}  ({time.time()-t0:.0f}s)")
t0 = time.time()
for i in range(len(involutions)):                       # Z_2 x Z_2
    gi = involutions[i]
    for j in range(i+1, len(involutions)):
        if prod(gi, involutions[j]) == prod(involutions[j], gi):
            H = closure([gi, involutions[j]])
            if H and len(H) == 4: subgroups.add(H)
print(f"  total subgroups of order 4: {len(subgroups)}  ({time.time()-t0:.0f}s)")

V = [H for H in subgroups if G['nondeg'](H)]
print(f"  nondegenerate: {len(V)}")
psc_gen.report_pool(G, V, k, "exhaustive enumeration")

# Save the enumerated pool before attempting the ILP. The enumeration is the
# expensive part and it is exhaustive, so it must survive a solver failure: at
# n = 8 the pool holds 4.8 million subgroups and CBC can abort while building
# the model, taking the whole run with it.
pool_file = f"pool_{n}{d}{k}.pkl"
pickle.dump([[[list(v), list(p)] for v, p in H] for H in V], open(pool_file, "wb"))
print(f"  pool written to {pool_file} ({len(V)} subgroups)")

import pulp
core = [H - {e} for H in V]; N = len(V)
prob = pulp.LpProblem("c", pulp.LpMaximize)
x = [pulp.LpVariable(f"x{i}", cat="Binary") for i in range(N)]
prob += pulp.lpSum(x)
if max_shared == 0:
    el2 = defaultdict(list)
    for i, c in enumerate(core):
        for el in c: el2[el].append(i)
    n_constraints = 0
    for vs in el2.values():
        if len(vs) >= 2: prob += pulp.lpSum(x[i] for i in vs) <= 1; n_constraints += 1
else:
    n_constraints = 0
    for i in range(N):
        for j in range(i+1, N):
            if len(core[i] & core[j]) > max_shared:
                prob += x[i] + x[j] <= 1; n_constraints += 1
print(f"\n  {n_constraints} constraints, solving ILP (limit {a.time_limit}s)...")
t0 = time.time()
tag = f"{n}{d}{k}"
log_path = f"cbc_{tag}_exact.log"
try:
    prob.solve(pulp.PULP_CBC_CMD(msg=a.verbose, timeLimit=a.time_limit,
                                 logPath=log_path))
    status = pulp.LpStatus[prob.status]
    # PuLP reports "Optimal" also when CBC stops on the time limit with a
    # feasible solution; only sol_status tells a proven optimum apart.
    if status == "Optimal" and prob.sol_status != pulp.LpSolutionOptimal:
        status = "Feasible (time limit, not proven optimal)"
    sel = [i for i in range(N) if pulp.value(x[i]) and pulp.value(x[i]) > 0.5]
except Exception as exc:
    # CBC aborts outright when the model is too large to build; the pool is
    # already on disk, so fall back to a randomized greedy pass, which still
    # yields a valid lower bound, and point at ilp_subpool.py for more.
    print(f"  CBC failed ({type(exc).__name__}); falling back to greedy")
    import random
    best = []
    for s in range(200):
        random.seed(s)
        order = list(range(N)); random.shuffle(order)
        used = set(); chosen = []
        for i in order:
            if core[i] & used: continue
            chosen.append(i); used |= core[i]
        if len(chosen) > len(best): best = chosen
    sel = best
    status = "CBC failed, greedy fallback"
    print(f"  for a better bound run:  python ilp_subpool.py --pool {pool_file} "
          f"--n {n} --d {d} --k {k} --aq {a.aq} --max-subpool 500000")
value = len(sel)
exact = (status == "Optimal")
print(f"\n===== A^P({n},{d},2) = {value}  [CBC {status}]  ({time.time()-t0:.0f}s) =====")

clique = [V[i] for i in sel]
cc = [H - {e} for H in clique]
ok_dist = all(len(cc[p] & cc[q]) <= max_shared for p in range(value) for q in range(p+1, value))
ok_group = all(all(prod(u, w) in H for u in H for w in H) for H in clique)
linear = sum(1 for H in clique if G['is_linear'](H))
print(f"  verification: distances={ok_dist} groups={ok_group} linear={linear}")
if not (ok_dist and ok_group):
    raise SystemExit("ABORTED: the clique failed verification; nothing written")
print(f"  factor {value/a.aq:.1f}x  (A_q={a.aq}" + (f", reference value {a.reference}" if a.reference else "") + ")")
print(f"  {'EXACT VALUE' if exact else 'lower bound (ILP did not prove optimality)'}")

# When CBC stops before proving optimality, its log still records the best
# upper bound it had established; the optimum then lies in [value, bound].
upper_bound = None
if not exact:
    try:
        m = re.search(r"Upper bound:\s*([-+0-9.eE]+)", open(log_path).read())
        if m:
            upper_bound = int(float(m.group(1)) + 1e-6)   # integral objective: floor
    except OSError:
        pass
    if upper_bound is not None:
        print(f"  CBC upper bound at stop: the optimum lies in [{value}, {upper_bound}]")
    else:
        print(f"  no upper bound found in {log_path}")

serialized = [[[list(v), list(p)] for v, p in sorted(H)] for H in clique]
pickle.dump(serialized, open(f"clique_{tag}_exact.pkl", "wb"))
json.dump(serialized, open(f"clique_{tag}_exact.json", "w"))
json.dump({"case": f"({n},{d},2)", "A_P": value, "status": status, "exact": exact,
           "method": f"exhaustive enumeration of U_{n} (k=2) + ILP (CBC)",
           "operation": "as in the paper, eq:Un", "n_nondegenerate_subgroups": N,
           "verification_distances": ok_dist, "verification_groups": ok_group,
           "linear": linear, "nonlinear": value-linear,
           "upper_bound": upper_bound, "cbc_log": log_path,
           "reference_value": a.reference, "A_q": a.aq},
          open(f"results_{tag}_exact.json", "w"), indent=2, ensure_ascii=False)
print(f"  written: results_{tag}_exact.json, clique_{tag}_exact.{{pkl,json}}")
